# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ubYKrE5xrM9GP8iyGvdopZzGy6HCe0pJ
"""

n=int(input())
arr=[]
for i in range(n):
  name=input("Enter user name")
  p=input("enter password")
  arr.append({name:p})
print(arr)
u1=input("enter name to validate")
p1=input("password")
found=False
for obj in arr:
  try:
    password=obj[u1]
    found=True
    if p1==password:
      print("Valid password")
    else:
      print("invalid password")
  except :
    pass
if found==False :
   print("user not found!")